import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { SessionWrapper } from "@/components/SessionWrapper";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { QueryProvider } from "@/providers/QueryProvider";


export const metadata = {
  title: "Note-Taking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <SessionWrapper>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </SessionWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
