import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { SessionWrapper } from "@/components/SessionWrapper";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { QueryProvider } from "@/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Note-Taking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <SessionWrapper>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </SessionWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
